#!/usr/bin/env node
// Generates the feature documentation from the catalog and from what the
// examples actually printed.
//
// Nothing here is written by hand: the code shown is the example file, and the
// output shown is the output that example produced in each installed runtime.
// Documentation therefore cannot drift from the library - if it did, the parity
// check would have failed first.
//
//   node scripts/generate-docs.mjs          write docs/
//   node scripts/generate-docs.mjs --check  fail if docs/ is out of date
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { runExamples } from './run-examples.mjs';
import { features, libraries, categories } from '../examples/features/catalog.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = path.join(root, 'docs');
const featuresDir = path.join(docsDir, 'features');
const siteDir = path.join(docsDir, 'site');

const checkOnly = process.argv.includes('--check');

const REPO = 'https://github.com/link-foundation/command-stream';

const generated = new Map();
function emit(relativePath, contents) {
  generated.set(relativePath, contents);
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function alternativeText(alternative) {
  if (!alternative) return null;
  if (typeof alternative === 'string') return { supported: true, code: alternative };
  return { supported: false, reason: alternative.unsupported };
}

// ---------------------------------------------------------------- feature page

function featurePage(feature, run, runtimes) {
  const lines = [];
  lines.push(`# ${feature.title}`);
  lines.push('');
  lines.push(feature.summary);
  lines.push('');
  lines.push(`**Category:** ${feature.category}  `);
  lines.push(`**API:** ${feature.api.map(name => `\`${name}\``).join(', ')}  `);
  lines.push(`**Runs in:** ${runtimes.map(runtime => runtime.label).join(', ')}`);
  lines.push('');
  lines.push('## Example');
  lines.push('');
  lines.push(`[\`${feature.file}\`](${REPO}/blob/main/${feature.file})`);
  lines.push('');
  lines.push('```js');
  lines.push(run.source.trimEnd());
  lines.push('```');
  lines.push('');
  lines.push('## Output');
  lines.push('');

  const reports = runtimes.map(runtime => run.runs[runtime.id]?.report ?? '');
  const identical = reports.every(report => report === reports[0]);

  if (identical) {
    lines.push(`Identical in ${runtimes.map(runtime => `${runtime.label} ${runtime.version}`).join(', ')}:`);
    lines.push('');
    lines.push('```');
    lines.push(reports[0].trimEnd());
    lines.push('```');
  } else {
    for (const [index, runtime] of runtimes.entries()) {
      lines.push(`### ${runtime.label} ${runtime.version}`);
      lines.push('');
      lines.push('```');
      lines.push(reports[index].trimEnd());
      lines.push('```');
      lines.push('');
    }
  }
  lines.push('');
  lines.push('## The same thing in other libraries');
  lines.push('');

  for (const library of libraries.filter(library => library.id !== 'command-stream')) {
    const alternative = alternativeText(feature.alternatives[library.id]);
    lines.push(`### [${library.name}](${library.url})`);
    lines.push('');
    if (!alternative) {
      lines.push('_Not compared._');
    } else if (alternative.supported) {
      lines.push('```js');
      lines.push(alternative.code);
      lines.push('```');
    } else {
      lines.push(`Not supported — ${alternative.reason}.`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('[← All features](../README.md)');
  lines.push('');
  return lines.join('\n');
}

// ----------------------------------------------------------------- index page

function indexPage(report) {
  const { runtimes } = report;
  const lines = [];
  lines.push('# Feature documentation');
  lines.push('');
  lines.push('Every feature of command-stream, with a runnable example, the output that');
  lines.push('example produced in each runtime, and the same thing written with the other');
  lines.push('shell libraries.');
  lines.push('');
  lines.push('This file is generated by `node scripts/generate-docs.mjs`. Edit the examples in');
  lines.push('`examples/features/` or the catalog in `examples/features/catalog.mjs` instead.');
  lines.push('');
  lines.push('## Runtime parity');
  lines.push('');
  lines.push(`All ${report.features.length} examples were executed in ${runtimes.map(runtime => `${runtime.label} ${runtime.version}`).join(', ')}.`);
  lines.push('');
  lines.push(`| Feature | ${runtimes.map(runtime => runtime.label).join(' | ')} |`);
  lines.push(`| --- | ${runtimes.map(() => '---').join(' | ')} |`);
  for (const run of report.features) {
    const feature = features.find(entry => entry.id === run.id);
    const cells = runtimes.map(runtime => (run.runs[runtime.id]?.failed ? '✗' : '✓'));
    lines.push(`| [${feature.title}](features/${feature.id}.md) | ${cells.join(' | ')} |`);
  }
  lines.push('');
  lines.push('## Library comparison');
  lines.push('');
  lines.push('✓ supported, — not supported. Follow a feature for the code in each library.');
  lines.push('');
  const others = libraries.filter(library => library.id !== 'command-stream');
  lines.push(`| Feature | command-stream | ${others.map(library => library.name).join(' | ')} |`);
  lines.push(`| --- | --- | ${others.map(() => '---').join(' | ')} |`);
  for (const feature of features) {
    const cells = others.map(library => {
      const alternative = alternativeText(feature.alternatives[library.id]);
      return alternative?.supported ? '✓' : '—';
    });
    lines.push(`| [${feature.title}](features/${feature.id}.md) | ✓ | ${cells.join(' | ')} |`);
  }
  lines.push('');
  lines.push('## Features by category');
  lines.push('');
  for (const category of categories) {
    const inCategory = features.filter(feature => feature.category === category);
    if (inCategory.length === 0) continue;
    lines.push(`### ${category}`);
    lines.push('');
    for (const feature of inCategory) {
      lines.push(`- [${feature.title}](features/${feature.id}.md) — ${feature.summary}`);
    }
    lines.push('');
  }
  lines.push('## Libraries compared');
  lines.push('');
  lines.push('| Library | Version | Runs in |');
  lines.push('| --- | --- | --- |');
  for (const library of libraries) {
    lines.push(`| [${library.name}](${library.url}) | ${library.version ?? 'this repository'} | ${library.runtimes.join(', ')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

// -------------------------------------------------------------------- website

function website(report) {
  const others = libraries.filter(library => library.id !== 'command-stream');
  const data = {
    runtimes: report.runtimes.map(runtime => ({ id: runtime.id, label: runtime.label, version: runtime.version })),
    libraries,
    categories,
    features: features.map(feature => {
      const run = report.features.find(entry => entry.id === feature.id);
      const reports = report.runtimes.map(runtime => run.runs[runtime.id]?.report ?? '');
      return {
        ...feature,
        source: run.source.trimEnd(),
        identicalOutput: reports.every(text => text === reports[0]),
        output: Object.fromEntries(report.runtimes.map((runtime, index) => [runtime.id, reports[index].trimEnd()])),
      };
    }),
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>command-stream — feature comparison</title>
<style>
:root { color-scheme: light dark; --line: #8883; }
* { box-sizing: border-box; }
body { margin: 0; font: 15px/1.55 system-ui, sans-serif; }
header { padding: 2rem 1.5rem 1rem; border-bottom: 1px solid var(--line); }
h1 { margin: 0 0 .25rem; font-size: 1.5rem; }
p.lede { margin: 0; opacity: .75; }
main { display: grid; grid-template-columns: 17rem 1fr; min-height: 60vh; }
nav { border-right: 1px solid var(--line); padding: 1rem; }
nav input { width: 100%; padding: .45rem .6rem; margin-bottom: .75rem; border: 1px solid var(--line); border-radius: .35rem; background: transparent; color: inherit; font: inherit; }
nav h2 { font-size: .75rem; text-transform: uppercase; letter-spacing: .06em; opacity: .6; margin: 1rem 0 .35rem; }
nav a { display: block; padding: .2rem .35rem; border-radius: .25rem; text-decoration: none; color: inherit; }
nav a:hover, nav a.active { background: #8882; }
section { padding: 1.5rem; max-width: 60rem; }
table { border-collapse: collapse; width: 100%; margin: .5rem 0 1.5rem; }
th, td { border: 1px solid var(--line); padding: .35rem .5rem; text-align: left; }
pre { background: #8881; padding: .75rem; border-radius: .4rem; overflow-x: auto; }
code { font-family: ui-monospace, monospace; font-size: .86em; }
.badge { display: inline-block; padding: .1rem .45rem; border: 1px solid var(--line); border-radius: 999px; font-size: .75rem; }
.unsupported { opacity: .7; font-style: italic; }
footer { padding: 1rem 1.5rem 3rem; opacity: .7; font-size: .85rem; }
@media (max-width: 720px) { main { grid-template-columns: 1fr; } nav { border-right: 0; border-bottom: 1px solid var(--line); } }
</style>
</head>
<body>
<header>
  <h1>command-stream — feature comparison</h1>
  <p class="lede">Every feature, the output it produced in each runtime, and the same thing in other shell libraries.</p>
</header>
<main>
  <nav>
    <input id="filter" type="search" placeholder="Filter features" aria-label="Filter features">
    <a href="#overview">Overview</a>
    <div id="nav-links"></div>
  </nav>
  <section id="content"></section>
</main>
<footer>Generated by <code>node scripts/generate-docs.mjs</code> from <code>examples/features/</code>.</footer>
<script id="data" type="application/json">${JSON.stringify(data).replace(/</g, '\\u003c')}</script>
<script>
const data = JSON.parse(document.getElementById('data').textContent);
const others = data.libraries.filter(library => library.id !== 'command-stream');
const byId = new Map(data.features.map(feature => [feature.id, feature]));

const escape = text => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function renderNav(query) {
  const needle = query.trim().toLowerCase();
  const html = data.categories.map(category => {
    const matches = data.features.filter(feature =>
      feature.category === category &&
      (needle === '' || (feature.title + ' ' + feature.summary + ' ' + feature.api.join(' ')).toLowerCase().includes(needle)));
    if (matches.length === 0) return '';
    return '<h2>' + escape(category) + '</h2>' +
      matches.map(feature => '<a href="#' + feature.id + '">' + escape(feature.title) + '</a>').join('');
  }).join('');
  document.getElementById('nav-links').innerHTML = html;
  markActive();
}

function markActive() {
  const current = location.hash.slice(1);
  for (const link of document.querySelectorAll('nav a')) {
    link.classList.toggle('active', link.getAttribute('href') === '#' + current);
  }
}

function overview() {
  const runtimeHeader = data.runtimes.map(runtime => '<th>' + escape(runtime.label) + ' ' + escape(runtime.version) + '</th>').join('');
  const runtimeRows = data.features.map(feature =>
    '<tr><td><a href="#' + feature.id + '">' + escape(feature.title) + '</a></td>' +
    data.runtimes.map(() => '<td>&#10003;</td>').join('') + '</tr>').join('');

  const libraryHeader = others.map(library => '<th>' + escape(library.name) + '</th>').join('');
  const libraryRows = data.features.map(feature =>
    '<tr><td><a href="#' + feature.id + '">' + escape(feature.title) + '</a></td><td>&#10003;</td>' +
    others.map(library => {
      const alternative = feature.alternatives[library.id];
      const supported = typeof alternative === 'string';
      return '<td>' + (supported ? '&#10003;' : '&mdash;') + '</td>';
    }).join('') + '</tr>').join('');

  return '<h2>Runtime parity</h2>' +
    '<p>Every example below was executed in each runtime and produced the same output.</p>' +
    '<table><thead><tr><th>Feature</th>' + runtimeHeader + '</tr></thead><tbody>' + runtimeRows + '</tbody></table>' +
    '<h2>Library comparison</h2>' +
    '<table><thead><tr><th>Feature</th><th>command-stream</th>' + libraryHeader + '</tr></thead><tbody>' + libraryRows + '</tbody></table>';
}

function featureView(feature) {
  const output = feature.identicalOutput
    ? '<p>Identical in ' + data.runtimes.map(runtime => escape(runtime.label) + ' ' + escape(runtime.version)).join(', ') + ':</p><pre><code>' + escape(feature.output[data.runtimes[0].id]) + '</code></pre>'
    : data.runtimes.map(runtime => '<h4>' + escape(runtime.label) + '</h4><pre><code>' + escape(feature.output[runtime.id]) + '</code></pre>').join('');

  const comparison = others.map(library => {
    const alternative = feature.alternatives[library.id];
    const body = typeof alternative === 'string'
      ? '<pre><code>' + escape(alternative) + '</code></pre>'
      : '<p class="unsupported">Not supported &mdash; ' + escape(alternative.unsupported) + '.</p>';
    return '<h4><a href="' + library.url + '">' + escape(library.name) + '</a></h4>' + body;
  }).join('');

  return '<h2>' + escape(feature.title) + '</h2>' +
    '<p>' + escape(feature.summary) + '</p>' +
    '<p><span class="badge">' + escape(feature.category) + '</span> ' +
    feature.api.map(name => '<span class="badge"><code>' + escape(name) + '</code></span>').join(' ') + '</p>' +
    '<h3>Example</h3><pre><code>' + escape(feature.source) + '</code></pre>' +
    '<h3>Output</h3>' + output +
    '<h3>The same thing in other libraries</h3>' + comparison;
}

function render() {
  const id = location.hash.slice(1);
  const feature = byId.get(id);
  document.getElementById('content').innerHTML = feature ? featureView(feature) : overview();
  markActive();
  window.scrollTo(0, 0);
}

document.getElementById('filter').addEventListener('input', event => renderNav(event.target.value));
window.addEventListener('hashchange', render);
renderNav('');
render();
</script>
</body>
</html>
`;
}

// ------------------------------------------------------------------ generate

const report = await runExamples();

const broken = report.features.filter(feature => !feature.parity);
if (broken.length > 0) {
  console.error(`Refusing to document behaviour that differs between runtimes: ${broken.map(feature => feature.id).join(', ')}`);
  console.error('Run `node scripts/check-parity.mjs` to see the differences.');
  process.exit(1);
}

for (const feature of features) {
  const run = report.features.find(entry => entry.id === feature.id);
  emit(path.join('docs', 'features', `${feature.id}.md`), featurePage(feature, run, report.runtimes));
}
emit(path.join('docs', 'README.md'), indexPage(report));
emit(path.join('docs', 'site', 'index.html'), website(report));

if (checkOnly) {
  const stale = [];
  for (const [relativePath, contents] of generated) {
    const absolute = path.join(root, relativePath);
    if (!fs.existsSync(absolute) || fs.readFileSync(absolute, 'utf8') !== contents) {
      stale.push(relativePath);
    }
  }
  if (stale.length > 0) {
    console.error('Generated documentation is out of date:');
    for (const file of stale) console.error(`  ${file}`);
    console.error('\nRun `node scripts/generate-docs.mjs` and commit the result.');
    process.exit(1);
  }
  console.log(`Documentation is up to date (${generated.size} files).`);
} else {
  fs.mkdirSync(featuresDir, { recursive: true });
  fs.mkdirSync(siteDir, { recursive: true });
  for (const [relativePath, contents] of generated) {
    fs.writeFileSync(path.join(root, relativePath), contents);
  }
  console.log(`Wrote ${generated.size} files to docs/.`);
}
