import { test, expect } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

async function runSyncVersion(args) {
  const subprocess = Bun.spawn(
    ['bun', 'scripts/sync-rust-version.mjs', ...args],
    {
      cwd: repoRoot,
      stdout: 'pipe',
      stderr: 'pipe',
    }
  );

  const [status, stdout, stderr] = await Promise.all([
    subprocess.exited,
    new Response(subprocess.stdout).text(),
    new Response(subprocess.stderr).text(),
  ]);

  return { status, stdout, stderr };
}

test('sync-rust-version updates Cargo.toml and Cargo.lock package versions', async () => {
  const tempDir = mkdtempSync(join(tmpdir(), 'command-stream-version-'));
  const packageJsonPath = join(tempDir, 'package.json');
  const cargoTomlPath = join(tempDir, 'Cargo.toml');
  const cargoLockPath = join(tempDir, 'Cargo.lock');

  try {
    writeFileSync(
      packageJsonPath,
      JSON.stringify({ name: 'command-stream', version: '1.2.3' })
    );
    writeFileSync(
      cargoTomlPath,
      `[package]
name = "command-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
`
    );
    writeFileSync(
      cargoLockPath,
      `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "some-dependency"
version = "9.9.9"

[[package]]
name = "command-stream"
version = "0.1.0"
dependencies = [
 "some-dependency",
]
`
    );

    const result = await runSyncVersion([
      '--package-json',
      packageJsonPath,
      '--cargo-toml',
      cargoTomlPath,
      '--cargo-lock',
      cargoLockPath,
    ]);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('0.1.0 -> 1.2.3');
    expect(readFileSync(cargoTomlPath, 'utf8')).toContain('version = "1.2.3"');

    const cargoLock = readFileSync(cargoLockPath, 'utf8');
    expect(cargoLock).toContain(`name = "some-dependency"\nversion = "9.9.9"`);
    expect(cargoLock).toContain(`name = "command-stream"\nversion = "1.2.3"`);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
});
